gText_Birch_Welcome::
	.string "DAD: Hello, my child.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I found an Eevee in the garage again.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Oh, right!\n"
	.string "It's almost your big day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's create your character...$"

gText_Birch_BoyOrGirl::
	.string "Do you look like this?\n"
	.string "Or like that?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Oh, of course...\p"
	.string "You're my child, {PLAYER}{KUN}.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "You're starting your adventure\n"
	.string "tomorrow...\p"
	.string "$"
